# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: mongoid-tree-rational 2.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "mongoid-tree-rational"
  s.version = "2.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Leif Ringstad", "Benedikt Deicke"]
  s.date = "2014-08-19"
  s.description = "A tree structure for Mongoid documents using the materialized path pattern and rational number sorting."
  s.email = "leifcr@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".rspec",
    ".travis.yml",
    "Gemfile",
    "Guardfile",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/mongoid/locale/en.yml",
    "lib/mongoid/locale/nb.yml",
    "lib/mongoid/tree.rb",
    "lib/mongoid/tree/ordering.rb",
    "lib/mongoid/tree/rational_numbering.rb",
    "lib/mongoid/tree/traversal.rb",
    "mongoid-tree-rational.gemspec",
    "spec/mongoid/tree/ordering_spec.rb",
    "spec/mongoid/tree/rational_numbering_spec.rb",
    "spec/mongoid/tree/traversal_spec.rb",
    "spec/mongoid/tree_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/macros/tree_macros.rb",
    "spec/support/models/node.rb"
  ]
  s.homepage = "https://github.com/boxcms/mongoid-tree-rational"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "A tree structure for Mongoid documents with rational numbers"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mongoid>, ["<= 5.0", ">= 4.0"])
      s.add_runtime_dependency(%q<rational_number>, [">= 0"])
      s.add_runtime_dependency(%q<rubysl-rake>, ["~> 2.0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<guard-rspec>, [">= 2.6.0"])
      s.add_development_dependency(%q<rb-inotify>, [">= 0"])
      s.add_development_dependency(%q<rb-fsevent>, [">= 0"])
      s.add_development_dependency(%q<wdm>, [">= 0"])
      s.add_development_dependency(%q<hirb>, [">= 0"])
      s.add_development_dependency(%q<wirble>, [">= 0"])
      s.add_development_dependency(%q<awesome_print>, [">= 0"])
      s.add_development_dependency(%q<coveralls>, [">= 0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<mongoid>, ["<= 5.0", ">= 4.0"])
      s.add_dependency(%q<rational_number>, [">= 0"])
      s.add_dependency(%q<rubysl-rake>, ["~> 2.0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<guard-rspec>, [">= 2.6.0"])
      s.add_dependency(%q<rb-inotify>, [">= 0"])
      s.add_dependency(%q<rb-fsevent>, [">= 0"])
      s.add_dependency(%q<wdm>, [">= 0"])
      s.add_dependency(%q<hirb>, [">= 0"])
      s.add_dependency(%q<wirble>, [">= 0"])
      s.add_dependency(%q<awesome_print>, [">= 0"])
      s.add_dependency(%q<coveralls>, [">= 0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<mongoid>, ["<= 5.0", ">= 4.0"])
    s.add_dependency(%q<rational_number>, [">= 0"])
    s.add_dependency(%q<rubysl-rake>, ["~> 2.0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<guard-rspec>, [">= 2.6.0"])
    s.add_dependency(%q<rb-inotify>, [">= 0"])
    s.add_dependency(%q<rb-fsevent>, [">= 0"])
    s.add_dependency(%q<wdm>, [">= 0"])
    s.add_dependency(%q<hirb>, [">= 0"])
    s.add_dependency(%q<wirble>, [">= 0"])
    s.add_dependency(%q<awesome_print>, [">= 0"])
    s.add_dependency(%q<coveralls>, [">= 0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

